'use client'

import { useEffect, useRef, useState } from 'react'
import { Camera, Plus, ShieldCheck, X } from 'lucide-react'
import { BtnPrimary, CIAInsightCard, GlassCard, HifiShell, IconButton, PaywallLock, Provenance, SolidCard, TopBar, TrendChart, cx } from '@/components/hifi/kit'
import { E1Modal } from './E1Modal'

const STATES = ['default', 'monthly', 'yearly-lock', 'photo-consent', 'photo-detail', 'empty', 'offline', 'history-detail'] as const
type ProgressState = (typeof STATES)[number]
type Panel = 'closed' | 'photo-consent' | 'photo-detail' | 'history-detail' | 'add'
function isState(value: string | null): value is ProgressState { return STATES.some(item => item === value) }

const HISTORY = [
  { date: 'Jul 6', iso: '2026-07-06', value: '176.4 lb', source: 'Smart scale', freshness: '10 days ago', confidence: 'High' },
  { date: 'Jun 29', iso: '2026-06-29', value: '177.1 lb', source: 'Smart scale', freshness: '17 days ago', confidence: 'High' },
  { date: 'Jun 22', iso: '2026-06-22', value: '177.8 lb', source: 'Manual entry', freshness: '24 days ago', confidence: 'Member-entered' },
] as const

function Dialog({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) {
  return <E1Modal label={title} onClose={onClose}><div className="flex min-h-11 items-center justify-between"><h2 className="text-[18px] font-semibold">{title}</h2><button type="button" aria-label={`Close ${title}`} className="focus-ring flex h-11 w-11 items-center justify-center rounded-full" onClick={onClose}><X/></button></div>{children}</E1Modal>
}

function Silhouette({ label }: { label: string }) { return <div className="relative aspect-square overflow-hidden rounded-xl border border-white/10 bg-ink-900" role="img" aria-label={`${label} neutral, non-identifiable code-native progress silhouette`}><div className="absolute left-1/2 top-[18%] h-[19%] w-[19%] -translate-x-1/2 rounded-full bg-paper-100/20"/><div className="absolute bottom-[8%] left-1/2 h-[54%] w-[42%] -translate-x-1/2 rounded-[45%_45%_25%_25%] bg-paper-100/15"/><span className="absolute bottom-2 left-2 rounded-pill bg-ink-900/80 px-2 py-1 text-[11px] text-paper-100/75">{label}</span></div> }

export function S90ProgressMeasurements() {
  const [state, setState] = useState<ProgressState>('default')
  const [panel, setPanel] = useState<Panel>('closed')
  const [timeframe, setTimeframe] = useState<'Weekly' | 'Monthly'>('Weekly')
  const [metric, setMetric] = useState<'Weight' | 'BMI' | 'Measurements'>('Weight')
  const [selectedHistory, setSelectedHistory] = useState(0)
  const [photoConsent, setPhotoConsent] = useState(false)
  const [status, setStatus] = useState('Bundled progress fixture only. No health provider, photo library, file, account, or network capability is active.')
  const returnFocus = useRef<HTMLButtonElement | null>(null)

  useEffect(() => { const params = new URLSearchParams(window.location.search); queueMicrotask(() => { if (isState(params.get('state'))) { const next = params.get('state') as ProgressState; setState(next); if (next === 'monthly') setTimeframe('Monthly'); if (next === 'photo-consent' || next === 'photo-detail' || next === 'history-detail') setPanel(next) } }) }, [])
  const closePanel = () => { setPanel('closed'); requestAnimationFrame(() => { if (returnFocus.current?.isConnected) returnFocus.current.focus() }) }
  const openPanel = (next: Exclude<Panel, 'closed'>, trigger: HTMLButtonElement) => { returnFocus.current = trigger; setPanel(next) }
  const empty = state === 'empty'
  const offline = state === 'offline'
  const yearly = state === 'yearly-lock'

  const photoPrivacy = <><p className="mt-2 text-[13px] leading-5 text-paper-100/75">HIFI-90-01 uses neutral code-native silhouettes only—no body bitmap, face, device photo, or file access.</p><dl className="mt-4 grid grid-cols-[auto_1fr] gap-x-3 gap-y-2 text-[12px] leading-5"><dt className="font-semibold">Storage</dt><dd>Local preview only; cloud sync off</dd><dt className="font-semibold">Backups</dt><dd>Off in this preview</dd><dt className="font-semibold">Retention</dt><dd>30 days after local revoke</dd><dt className="font-semibold">Training</dt><dd>Never used for model training</dd><dt className="font-semibold">Review</dt><dd>No human review by default</dd><dt className="font-semibold">Sharing</dt><dd>Off by default</dd></dl></>
  const overlay = panel === 'photo-consent' ? <Dialog title="Progress photo consent" onClose={closePanel}>{photoPrivacy}<div className="mt-4 grid grid-cols-2 gap-2"><button type="button" className="focus-ring min-h-11 rounded-pill bg-brand-orange px-3 text-[12px] font-semibold text-ink-900" onClick={() => { setPhotoConsent(true); setPanel('photo-detail'); setStatus('Photo silhouette preview consented locally. No file or image was accessed.') }}>Allow local preview</button><button type="button" className="focus-ring min-h-11 rounded-pill border border-white/15 px-3 text-[12px]" onClick={closePanel}>Not now</button></div></Dialog>
  : panel === 'photo-detail' ? <Dialog title="Private photo comparison" onClose={closePanel}>{photoPrivacy}{photoConsent || state === 'photo-detail' ? <><div className="mt-4 grid grid-cols-2 gap-3" data-asset-disposition="HIFI-90-01-code-native"><Silhouette label="Before · Jun 1"/><Silhouette label="Now · Jul 6"/></div><div className="mt-4 grid grid-cols-2 gap-2">{['Export preview', 'Revoke access', 'Delete selected', 'Retention details'].map(action => <button type="button" key={action} className="focus-ring min-h-11 rounded-pill border border-white/15 px-2 text-[12px]" onClick={() => setStatus(`${action} completed in the local preview only. No photo or account data changed.`)}>{action}</button>)}</div></> : <p className="mt-4 rounded-xl border border-white/10 p-4 text-[13px] text-paper-100/70">No sensitive image is shown before consent.</p>}<p className="mt-3 text-[12px] text-paper-100/70" role="status">{status}</p></Dialog>
  : panel === 'history-detail' ? <Dialog title="Measurement details" onClose={closePanel}><div className="mt-3 space-y-2">{HISTORY.map((row, index) => <button key={row.iso} type="button" aria-pressed={selectedHistory === index} className={cx('focus-ring w-full rounded-xl border p-3 text-left text-[12px]', selectedHistory === index ? 'border-brand-orange bg-brand-orange/10' : 'border-white/10')} onClick={() => setSelectedHistory(index)}><strong className="text-[14px]">{row.value}</strong><span className="block mt-1 text-paper-100/70">{row.date} · {row.source} · {row.freshness} · {row.confidence} confidence</span></button>)}</div><p className="mt-3 text-[12px] leading-5 text-paper-100/70">Selected measurement: {HISTORY[selectedHistory].value}. Source and confidence are inspectable; no edits are persisted.</p></Dialog>
  : panel === 'add' ? <Dialog title="Add measurement" onClose={closePanel}><p className="mt-2 text-[13px] leading-5 text-paper-100/75">Stores value, unit, date, and source in this preview. You can delete it from History. Nothing syncs or leaves this screen.</p><label className="mt-4 block text-[12px] font-semibold" htmlFor="measurement-value">Weight in pounds</label><input id="measurement-value" inputMode="decimal" defaultValue="176.2" className="focus-ring mt-2 h-12 w-full rounded-xl border border-white/15 bg-ink-900 px-4 text-paper-100"/><button type="button" className="focus-ring mt-4 min-h-11 w-full rounded-pill bg-brand-orange font-semibold text-ink-900" onClick={() => { setStatus('176.2 lb appended to the local preview history with source Manual entry.'); closePanel() }}>Save local measurement</button></Dialog> : undefined

  return <HifiShell header={<TopBar title="Progress" backHref="/screens/17" right={<IconButton label="Add measurement" onClick={event => openPanel('add', event.currentTarget)}><Plus size={19}/></IconButton>}/>} atmosphere="you" activeTab="me" overlay={overlay}><main className="space-y-4 px-4 pb-6 pt-3" data-state-surface={state} data-progress-state={state} data-progress-panel={panel} data-timeframe={yearly ? 'Yearly' : timeframe} data-metric={metric} data-photo-consent={photoConsent} data-asset-disposition="HIFI-90-01-code-native-no-raster">
    {offline && <div className="rounded-xl border border-white/10 bg-white/[0.04] p-3 text-[12px] text-paper-100/75">Offline · cached smart-scale chart from Jul 6. Provider retry is unavailable; cached values remain labelled.</div>}
    {empty && <div className="rounded-[28px] border border-dashed border-white/15 p-6 text-center"><h2 className="text-[18px] font-semibold">Log your first measurement</h2><p className="mt-2 text-[13px] leading-5 text-paper-100/65">Start tracking trends without fabricated values.</p><button type="button" className="focus-ring mt-4 min-h-11 rounded-pill bg-brand-orange px-5 font-semibold text-ink-900" onClick={event => openPanel('add', event.currentTarget)}>Add measurement</button></div>}
    {!empty && <>
      <div role="tablist" aria-label="Timeframe" className="grid grid-cols-3 gap-1 rounded-pill border border-white/10 bg-white/[0.03] p-1">{(['Weekly', 'Monthly'] as const).map(tab => <button key={tab} type="button" role="tab" aria-selected={!yearly && timeframe === tab} className={cx('focus-ring min-h-11 rounded-pill px-2 text-[13px] font-semibold', !yearly && timeframe === tab ? 'bg-white/10 text-paper-100' : 'text-paper-100/65')} onClick={() => { setState(tab === 'Monthly' ? 'monthly' : 'default'); setTimeframe(tab) }}>{tab}</button>)}<button type="button" role="tab" aria-selected={yearly} className={cx('focus-ring min-h-11 rounded-pill px-2 text-[13px] font-semibold', yearly ? 'bg-white/10 text-paper-100' : 'text-paper-100/65')} onClick={() => setState('yearly-lock')}>Yearly</button></div>
      {yearly ? <PaywallLock title="Yearly trends" description="See 12-month comparisons and projected mission bands with Premium." action={<BtnPrimary onClick={() => setStatus('Premium unlock preview selected locally. No purchase or navigation occurred.')}>Unlock with premium</BtnPrimary>}><TrendChart past={[184,182,181,179,178,176]} projected={[175,174]} label="Blurred yearly premium preview without member-sensitive labels"/></PaywallLock>
      : <GlassCard tone="you"><p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-brand-orange">{metric} trend</p><div className="mt-2 flex flex-wrap items-baseline gap-2"><span className="text-[36px] font-semibold tabular-nums">{metric === 'Weight' ? '176.4' : metric === 'BMI' ? '24.8' : '33.1'}</span><span className="text-[14px] text-paper-100/65">{metric === 'Weight' ? 'lb' : metric === 'BMI' ? 'BMI' : 'in waist'}</span></div><p className="mt-1 text-[13px] text-paper-100/70">{timeframe === 'Monthly' ? 'Down 2.6 across 6 weeks' : 'Down 1.2 this month'} · non-shaming trend</p><div className="mt-2"><Provenance items={metric === 'Weight' ? ['Smart scale', 'Jul 6', 'High confidence'] : metric === 'BMI' ? ['176.4 lb ÷ 70in² × 703', 'Jul 6', 'Calculated · high confidence'] : ['Manual tape', 'Jul 6', 'Member-entered']} /></div><div className="mt-4"><TrendChart past={timeframe === 'Monthly' ? [179,178.4,177.8,177.5,177.1,176.8,176.4] : [177.8,177.1,176.4]} projected={[176,175.6,175.2]} milestones={[timeframe === 'Monthly' ? 6 : 2]} height={110} label={`${timeframe} ${metric} trend. Solid orange values are actual, dashed purple values are projections, and the green dot is a milestone. Selected Jul 6: ${metric === 'Weight' ? '176.4 pounds, smart scale, high confidence' : metric}.`}/></div><div role="tablist" aria-label="Metric" className="mt-4 grid grid-cols-3 gap-1 rounded-pill border border-white/10 bg-ink-900 p-1">{(['Weight','BMI','Measurements'] as const).map(tab => <button key={tab} type="button" role="tab" aria-selected={metric === tab} className={cx('focus-ring min-h-11 rounded-pill px-1 text-[12px] font-medium', metric === tab ? 'bg-white/10 text-paper-100' : 'text-paper-100/65')} onClick={() => setMetric(tab)}>{tab}</button>)}</div></GlassCard>}
      <div className="grid grid-cols-1 gap-3 min-[360px]:grid-cols-2"><SolidCard><p className="text-[11px] font-semibold uppercase text-paper-100/65">BMI</p><p className="mt-1 text-[22px] font-semibold tabular-nums">24.8</p><p className="mt-1 text-[11px] leading-4 text-paper-100/65">176.4 lb ÷ 70in² × 703 · Smart scale + profile height · Jul 6 · high confidence</p></SolidCard><SolidCard><p className="text-[11px] font-semibold uppercase text-paper-100/65">Waist</p><p className="mt-1 text-[22px] font-semibold tabular-nums">33.1 in</p><p className="mt-1 text-[11px] leading-4 text-paper-100/65">Manual tape · Jul 6 · member-entered · target 62%</p></SolidCard></div>
      <button type="button" className="focus-ring w-full rounded-xl text-left" onClick={event => openPanel(photoConsent ? 'photo-detail' : 'photo-consent', event.currentTarget)}><SolidCard><div className="flex min-h-11 flex-wrap items-center justify-between gap-2"><span className="flex items-center gap-2 text-[13px]"><Camera className="h-4 w-4"/>Progress photos · 4</span><span className="text-[11px] text-paper-100/65">Private · local preview</span></div><p className="mt-1 text-[12px] text-paper-100/65">Open consent-gated HIFI-90-01 silhouette comparison</p></SolidCard></button>
      <SolidCard><ShieldCheck className="text-forest-green"/><h2 className="mt-2 text-[15px] font-semibold">Photos are private by default</h2><p className="mt-1 text-[12px] leading-5 text-paper-100/65">Code-native neutral silhouettes; no bitmap, file, face, cloud backup, model training, human review, or default sharing.</p><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" className="focus-ring min-h-11 rounded-pill border border-white/15 text-[12px]" onClick={event => openPanel('photo-consent', event.currentTarget)}>Consent</button><button type="button" className="focus-ring min-h-11 rounded-pill border border-white/15 text-[12px]" onClick={event => openPanel('photo-detail', event.currentTarget)}>Privacy</button></div></SolidCard>
      <CIAInsightCard provenance={['Smart scale + Health', '42 paired nights', '6-week window', 'Fresh Jul 6', 'Medium confidence']}><p>Weight and sleep moved alongside each other in this sample. Keep the <span className="text-emphasis">pace</span> steady. This is not a causal or medical claim.</p></CIAInsightCard>
      <button type="button" className="focus-ring w-full rounded-xl text-left" onClick={event => openPanel('history-detail', event.currentTarget)}><SolidCard><div className="flex min-h-11 items-center justify-between gap-3"><span className="text-[13px] font-semibold">Measurement history</span><span className="text-[12px] text-brand-orange">Review 3 entries</span></div><p className="mt-1 text-[12px] text-paper-100/65">Latest: 176.4 lb · Jul 6 · Smart scale · high confidence</p></SolidCard></button>
    </>}
    <p className="text-[12px] leading-5 text-paper-100/65" role="status">{status}</p>
  </main></HifiShell>
}
