'use client'

import { useEffect, useState } from 'react'
import { MoreHorizontal, Shield, X } from 'lucide-react'
import Link from 'next/link'
import { BtnPrimary, CIAInsightCard, ChargeMeter, Chip, ConsentRail, FULL_DATA_CONTROLS, GlassCard, GlassPillInput, HifiShell, ProgressRing, Provenance, SafetyCard, SolidCard, TopBar, TrendChart } from '@/components/hifi/kit'
import { E1Modal } from '../intelligence/E1Modal'

const STATES = ['default', 'empty', 'low-confidence', 'error-whoop', 'offline', 'log-success', 'log-disabled', 'safety-open', 'privacy-controls'] as const
type StressState = (typeof STATES)[number]
function isState(value: string | null): value is StressState { return STATES.some(state => state === value) }
function Dialog({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <E1Modal label={title} onClose={onClose}><div className="flex min-h-11 items-center justify-between"><h2 className="text-[18px] font-semibold">{title}</h2><button type="button" aria-label={`Close ${title}`} className="focus-ring flex h-11 w-11 items-center justify-center rounded-full" onClick={onClose}><X /></button></div>{children}</E1Modal> }

export function S52StressManagement() {
  const [state, setState] = useState<StressState>('default')
  const [stress, setStress] = useState(5)
  const [trigger, setTrigger] = useState('')
  const [status, setStatus] = useState('Local visual fixture only. No WHOOP, health provider, account, network, or emergency calling capability is active.')
  const [panel, setPanel] = useState<'closed' | 'safety-open' | 'privacy-controls'>('closed')
  useEffect(() => { const value = new URLSearchParams(window.location.search).get('state'); queueMicrotask(() => { if (isState(value)) { setState(value); if (value === 'safety-open' || value === 'privacy-controls') setPanel(value) } }) }, [])
  const empty = state === 'empty'
  const low = state === 'low-confidence'
  const unavailable = empty || state === 'error-whoop'
  const close = () => setPanel('closed')
  const overlay = panel === 'safety-open' ? <Dialog title="Crisis and local support" onClose={close}><p className="mt-2 text-[13px] leading-5 text-paper-100/75">If you may be in immediate danger, contact local emergency services. This visual prototype cannot place calls, send texts, or determine your location.</p><Link href="/screens/25?support=crisis" className="focus-ring mt-4 flex min-h-11 items-center justify-center rounded-pill border border-white/15 font-semibold">Open Help Center guidance</Link></Dialog>
    : panel === 'privacy-controls' ? <Dialog title="Stress data controls" onClose={close}><p className="mt-2 text-[13px] leading-5 text-paper-100/75">Health and private note preview · local scope · fresh today · displayed confidence only.</p><ConsentRail controls={FULL_DATA_CONTROLS} /><p className="mt-3 text-[12px] leading-5 text-paper-100/70">Notes remain local in this fixture. Export, revoke, and delete do not contact an account or provider.</p></Dialog> : undefined
  const submit = (event: React.FormEvent) => { event.preventDefault(); setState('log-success'); setStatus(`Stress check-in ${stress} of 10${trigger ? ` with ${trigger} trigger` : ''} saved in this local preview.`) }

  return <HifiShell header={<TopBar title={<>Stress <span className="text-emphasis">management</span></>} right={<button type="button" aria-label="Open crisis resources" className="focus-ring relative flex h-11 w-11 items-center justify-center rounded-full text-paper-100/70" onClick={() => setPanel('safety-open')}><MoreHorizontal /><Shield className="absolute bottom-1 right-1 h-3 w-3 text-brand-orange" /></button>} />} atmosphere="you" overlay={overlay}>
    <main className="space-y-4 px-4 pb-6 pt-3" data-stress-state={state} data-stress-value={stress}>
      {(state === 'offline' || state === 'error-whoop') && <SolidCard><p role="status" className="text-[13px] font-semibold">{state === 'offline' ? 'Offline · cached member check-ins only' : 'WHOOP data unavailable'}</p><p className="mt-1 text-[12px] text-paper-100/70">Manual stress logging remains available. No provider retry occurs in this prototype.</p></SolidCard>}
      <GlassCard tone="you"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-paper-100/70">Current stress level</p><Chip>{unavailable ? 'Honest null' : low ? 'Estimated · low confidence' : '3.2 out of 10'}</Chip></div><div className="mt-4 flex flex-col gap-4 min-[350px]:flex-row min-[350px]:items-center"><ProgressRing percent={unavailable ? 0 : 32} value={unavailable ? '—' : '3.2'} label={unavailable ? 'Log below' : 'Moderate'} tone="you" size={112} /><div className="min-w-0 flex-1 space-y-2 text-[13px]">{[['Body','2.1'],['Sleep','4.5'],['Behavior','3.0']].map(([label,value]) => <div key={label} className="flex justify-between"><span className="text-paper-100/65">{label}</span><span className="tabular-nums">{unavailable ? '—' : value}</span></div>)}</div></div><div className="mt-4 flex justify-between text-[13px]"><span>Mental capacity left today</span><span>{unavailable ? '—' : '60%'}</span></div><ChargeMeter filled={unavailable ? 0 : 6} ticks={10} /><div className="mt-3"><Provenance items={unavailable ? ['Manual check-in needed'] : ['Health composite mean: 3.2', 'Fresh today', low ? 'Low confidence' : 'High confidence']} /></div></GlassCard>
      <form onSubmit={submit}><SolidCard><h2 className="text-[11px] font-semibold uppercase tracking-[0.12em] text-paper-100/70">Quick log</h2><label htmlFor="stress-range" className="mt-3 block text-[15px]">How are you feeling? <strong>{stress} of 10</strong></label><input id="stress-range" type="range" min="1" max="10" step="1" value={stress} onChange={event => setStress(Number(event.target.value))} className="focus-ring mt-3 h-11 w-full accent-orange-500" aria-valuetext={`${stress} of 10, ${stress < 4 ? 'calm' : stress < 8 ? 'moderate' : 'overwhelmed'}`} /><div className="flex justify-between text-[12px] text-paper-100/65"><span>Calm</span><span>Overwhelmed</span></div><p className="mt-3 text-[12px] text-paper-100/70">Optional trigger</p><div className="mt-1 flex flex-wrap gap-2">{['Work','Time','Finance','Other'].map(item => <Chip key={item} interactive pressed={trigger === item} onClick={() => setTrigger(trigger === item ? '' : item)}>{item}</Chip>)}</div><div className="mt-3"><GlassPillInput name="note" placeholder="Add a private note" /></div><BtnPrimary className="mt-3 w-full" type="submit" disabled={state === 'log-disabled'}>{state === 'log-success' ? 'Logged locally' : state === 'log-disabled' ? 'Available in 00:30' : 'Log stress'}</BtnPrimary><p className="mt-2 text-center text-[12px] text-paper-100/70">Coaching support, not medical advice.</p></SolidCard></form>
      {!empty && <CIAInsightCard provenance={['4 member check-ins', '7-day window', low ? 'Low confidence' : 'Medium confidence']}><p>Work appeared most often in this small sample. A five-minute breathing break may support a <span className="text-emphasis">reset</span>; this is not a diagnosis.</p></CIAInsightCard>}
      <SolidCard><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-paper-100/70">Stress trend</p><Chip>7d actual</Chip></div><div className="mt-2 flex flex-wrap items-baseline gap-2"><span className="text-[24px] font-semibold tabular-nums">{empty ? '—' : '4.8'}</span><span className="text-[12px] text-paper-100/65">{empty ? 'Log your first check-in' : 'average · down 11% from 5.4 last week'}</span></div>{!empty && <TrendChart past={[5.2,5.4,4.8,4.6,4.2,4.7,4.7]} projected={[4.5,4.2,3.9]} height={80} label="Seven-day actual values average 4.8; dashed projection is low confidence" />}<div className="mt-3"><Provenance items={['You logged', 'Fresh today', 'Actual average 4.8']} /></div></SolidCard>
      <div className="grid grid-cols-1 gap-2 min-[350px]:grid-cols-2"><button type="button" className="focus-ring min-h-11 rounded-pill border border-white/15 text-[13px]" onClick={() => setStatus('Breathing tool selected locally. No session started.')}>Open breathing</button><button type="button" className="focus-ring min-h-11 rounded-pill border border-white/15 text-[13px]" onClick={() => setPanel('privacy-controls')}>Privacy controls</button></div>
      <SafetyCard href="/screens/25?support=crisis" />
      <p className="text-[12px] leading-5 text-paper-100/70" role="status">{status}</p>
    </main>
  </HifiShell>
}
