'use client'

import { useEffect, useState } from 'react'
import { Lock, Pause, Play, Wind, X } from 'lucide-react'
import { BtnPrimary, ConsentRail, FULL_DATA_CONTROLS, GlassCard, HifiShell, Provenance, SafetyCard, SolidCard, TopBar, cx } from '@/components/hifi/kit'
import { E1Modal } from '../intelligence/E1Modal'

const STATES = ['default', 'empty', 'library-error', 'active-inhale', 'active-hold-paused', 'session-success', 'rating-error', 'duration-locked', 'risky-technique-gate', 'offline'] as const
type BreathState = (typeof STATES)[number]
function isState(value: string | null): value is BreathState { return STATES.some(state => state === value) }
function Dialog({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <E1Modal label={title} onClose={onClose} className="!bg-ink-900 border border-white/15 shadow-2xl"><div className="flex min-h-11 items-center justify-between gap-2"><h2 className="min-w-0 text-[18px] font-semibold">{title}</h2><button type="button" aria-label={`Close ${title}`} className="focus-ring flex h-11 w-11 shrink-0 items-center justify-center rounded-full" onClick={onClose}><X /></button></div>{children}</E1Modal> }

const exercises = [
  ['Box breathing','4-4-4-4 · 5 min','Good for a paced focus break'],
  ['4-7-8 breathing','4-7-8 · 5 min','Stop if light-headed'],
  ['Coherent breathing','5-5 · 10 min','Gentle balanced pacing'],
  ['Higher-risk breath holds','30 breaths · review first','Hyperventilation and breath-hold warning required'],
  ['Alternate nostril','4-4-4 · 5 min','Gentle centering practice'],
] as const

export function S53BreathingExercises() {
  const [state, setState] = useState<BreathState>('default')
  const [filter, setFilter] = useState('All')
  const [duration, setDuration] = useState(5)
  const [phase, setPhase] = useState<'inhale' | 'hold'>('inhale')
  const [paused, setPaused] = useState(false)
  const [acknowledged, setAcknowledged] = useState(false)
  const [panel, setPanel] = useState<'closed' | 'risky-technique-gate' | 'privacy'>('closed')
  const [status, setStatus] = useState('Local visual fixture only. No sensor, haptic, media, account, health provider, or network capability is active.')
  useEffect(() => { const value = new URLSearchParams(window.location.search).get('state'); queueMicrotask(() => { if (isState(value)) { setState(value); if (value === 'active-hold-paused') { setPhase('hold'); setPaused(true) } else if (value === 'active-inhale') setPhase('inhale'); if (value === 'risky-technique-gate') setPanel('risky-technique-gate') } }) }, [])
  const active = state === 'active-inhale' || state === 'active-hold-paused'
  const close = () => setPanel('closed')
  const overlay = panel === 'risky-technique-gate' ? <Dialog title="Review before higher-risk breathing" onClose={close}><p className="mt-2 text-[13px] leading-5 text-paper-100/75">Rapid breathing and breath holds may cause dizziness or fainting. Do not practise in water, while driving, standing, pregnant, or with a condition a clinician says makes breath holds unsafe. Stop immediately for pain, tingling, dizziness, or distress.</p><label className="mt-4 flex min-h-11 items-center gap-3 rounded-xl border border-white/15 p-3 text-[13px]"><input type="checkbox" checked={acknowledged} onChange={event => setAcknowledged(event.target.checked)} className="h-11 w-11 shrink-0 accent-orange-500" />I understand this local safety preview</label><BtnPrimary className="mt-3 w-full" disabled={!acknowledged} onClick={() => { setState('active-inhale'); setPanel('closed'); setStatus('Higher-risk technique safety acknowledged locally. No clinical approval or device action is implied.') }}>Continue to paced preview</BtnPrimary></Dialog>
    : panel === 'privacy' ? <Dialog title="Breathing data controls" onClose={close}><p className="mt-2 text-[13px] leading-5 text-paper-100/75">Wellbeing practice history · local app source · fresh today · high confidence for member-entered sessions.</p><ConsentRail controls={FULL_DATA_CONTROLS} /><p className="mt-3 text-[12px] leading-5 text-paper-100/70">HIFI-53-01 is fulfilled by a code-native pacer and icons; no person, instructional bitmap, camera, or media file.</p></Dialog> : undefined

  return <HifiShell header={<TopBar title="Breathing exercises" eyebrow="Wellbeing" />} atmosphere="you" overlay={overlay}>
    <main className="space-y-4 px-4 pb-6 pt-3" data-breathing-state={state} data-pacer-phase={active ? phase : 'inactive'} data-pacer-paused={paused} data-asset-disposition="HIFI-53-01-code-native-pacer-no-person-media">
      {(state === 'offline' || state === 'library-error') && <SolidCard><p role="status" className="text-[13px] font-semibold">{state === 'offline' ? 'Offline · bundled techniques remain available' : 'Could not load practice history'}</p><p className="mt-1 text-[12px] text-paper-100/70">The local exercise library remains usable; no network retry occurs automatically.</p></SolidCard>}
      {active ? <GlassCard tone="cia"><button type="button" className="focus-ring flex min-h-[260px] w-full flex-col items-center justify-center rounded-[40px] text-center" aria-label={`Breathing pacer. Tap to ${paused ? 'resume' : 'pause'}. Current phase: ${phase}. ${paused ? 'Paused' : '4 seconds remaining'}.`} onClick={() => setPaused(value => !value)}><span className={cx('flex h-40 w-40 items-center justify-center rounded-full border border-royal-purple/60 bg-royal-purple/10 shadow-[var(--glow-purple-sm)] motion-safe:transition-transform motion-safe:duration-700', !paused && phase === 'inhale' && 'motion-safe:scale-110')}><Wind className="h-10 w-10 text-royal-purple" /></span><strong className="mt-5 text-[24px] uppercase tracking-[0.14em]">{paused ? 'Paused' : phase}</strong><span className="mt-2 text-[13px] text-paper-100/70">{paused ? 'Tap to resume' : '4 seconds · tap to pause'}</span></button><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" aria-label={paused ? 'Resume breathing phase' : 'Pause breathing phase'} className="focus-ring min-h-11 rounded-pill border border-white/15" onClick={() => { setPhase(phase === 'inhale' ? 'hold' : 'inhale'); setPaused(false) }}>{paused ? <Play className="mx-auto" /> : <Pause className="mx-auto" />}</button><button type="button" className="focus-ring min-h-11 rounded-pill border border-white/15 text-[13px]" onClick={() => setState('session-success')}>Complete session</button></div></GlassCard>
      : state === 'session-success' || state === 'rating-error' ? <SolidCard><p className="text-[18px] font-semibold">{state === 'session-success' ? 'Session complete' : 'Rating could not save'}</p><p className="mt-2 text-[13px] leading-5 text-paper-100/70">{state === 'session-success' ? 'Five local minutes added. No health outcome or XP is claimed.' : 'Your session remains complete. Try the local rating again.'}</p><div className="mt-3 grid grid-cols-3 gap-2">{[1,3,5].map(value => <button key={value} type="button" className="focus-ring min-h-11 rounded-pill border border-white/15" onClick={() => setStatus(`Rating ${value} selected locally.`)}>{value}</button>)}</div></SolidCard>
      : <>
        <GlassCard tone="you"><div className="flex flex-wrap items-end justify-between gap-3"><div><span className="text-[44px] font-semibold tabular-nums">{state === 'empty' ? '0' : '42'}</span><span className="ml-2 text-[13px] text-paper-100/65">Sessions</span></div><div><span className="text-[28px] font-semibold tabular-nums">{state === 'empty' ? '—' : '210'}</span><span className="ml-1 text-[12px] text-paper-100/65">Minutes</span></div></div><div className="mt-3"><Provenance items={state === 'empty' ? ['Start a local session'] : ['42 · local app · fresh today', '210 min · you logged · high confidence']} /></div><div className="mt-4"><div className="flex justify-between text-[12px] text-paper-100/70"><span>Consistency · 8 days</span><span>{state === 'empty' ? '0 of 8' : '5 of 8'}</span></div><div className="mt-2 grid grid-cols-8 gap-1" aria-label={`${state === 'empty' ? 0 : 5} of 8 practice days`}>{Array.from({ length: 8 }, (_, index) => <span key={index} className={cx('h-7 rounded-md', state !== 'empty' && index < 5 ? 'bg-brand-orange' : 'bg-white/[0.05]')} />)}</div></div></GlassCard>
        <div role="tablist" aria-label="Exercise filters" className="flex min-h-11 gap-2 overflow-x-auto">{['All','Sleep','Stress','Energy','Focus'].map(item => <button key={item} type="button" role="tab" aria-selected={filter === item} className={cx('focus-ring min-h-11 shrink-0 rounded-pill border px-4 text-[12px]', filter === item ? 'border-brand-orange bg-brand-orange/10 text-paper-100' : 'border-white/15 text-paper-100/70')} onClick={() => setFilter(item)}>{item}</button>)}</div>
        {state !== 'library-error' && <div className="space-y-2">{exercises.map(([name,meta,description], index) => <button key={name} type="button" className="focus-ring w-full rounded-xl text-left" onClick={() => index === 3 ? setPanel('risky-technique-gate') : setState('active-inhale')}><SolidCard><div className="flex min-h-14 items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-brand-orange/10"><Wind className="h-5 w-5 text-brand-orange" /></span><span className="min-w-0"><strong className="block text-[14px]">{name}</strong><span className="mt-1 block text-[12px] text-paper-100/70">{meta}</span><span className="mt-1 block text-[12px] leading-4 text-paper-100/70">{description}</span></span></div></SolidCard></button>)}</div>}
        <fieldset><legend className="text-[12px] font-semibold uppercase tracking-[0.1em] text-paper-100/70">Session length</legend><div className="mt-2 grid grid-cols-3 gap-2">{[3,5,10].map(value => <button key={value} type="button" role="radio" aria-checked={duration === value && value !== 10} disabled={value === 10} className={cx('focus-ring min-h-11 rounded-xl border text-[13px]', value === 10 ? 'border-white/10 text-paper-100/45' : duration === value ? 'border-brand-orange bg-brand-orange/10' : 'border-white/15')} onClick={() => setDuration(value)}>{value === 10 && <Lock className="mr-1 inline h-3 w-3" />}{value} min</button>)}</div><p className="mt-2 text-[11px] text-paper-100/65">10 min is a locked Plus preview; safety and base techniques remain free.</p></fieldset>
      </>}
      <div className="grid grid-cols-1 gap-2 min-[350px]:grid-cols-2"><button type="button" className="focus-ring min-h-11 rounded-pill border border-white/15 text-[13px]" onClick={() => setPanel('privacy')}>Data controls</button><button type="button" className="focus-ring min-h-11 rounded-pill border border-white/15 text-[13px]" onClick={() => setPanel('risky-technique-gate')}>Technique safety</button></div>
      <SafetyCard href="/screens/25?support=crisis" />
      <p className="text-[12px] leading-5 text-paper-100/70">Coaching support, not medical advice. <span role="status">{status}</span></p>
    </main>
  </HifiShell>
}
