'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { Camera, RotateCcw, Trash2, X } from 'lucide-react'
import { BtnGhost, BtnSecondary, Chip, ConsentRail, FULL_DATA_CONTROLS, GlassCard, HifiShell, Provenance, SolidCard, TopBar, cx } from '@/components/hifi/kit'
import { E1Modal } from '../intelligence/E1Modal'

const looks = [
  { id: 1, name: 'Linen evening look', shared: true, deleting: false, source: 'Upload retained 2d', render: '82% · May 21' },
  { id: 2, name: 'Workday clean fit', shared: false, deleting: false, source: 'Source deleted', render: '88% · May 21' },
  { id: 3, name: 'Studio neutral test', shared: false, deleting: true, source: 'Upload retained 1d', render: '64% · metadata partial' },
]
export function S87TryonHistory() {
  const [fixture, setFixture] = useState('default'); const [filter, setFilter] = useState('All'); const [panel, setPanel] = useState<'delete'|'data'|null>(null); const [selectedId, setSelectedId] = useState(1); const [status, setStatus] = useState('Three shown of seven saved looks. Local visual fixture only.')
  useEffect(() => { const q = new URLSearchParams(window.location.search).get('state') ?? 'default'; queueMicrotask(() => { setFixture(q); setFilter(q === 'filter-shared' ? 'Shared' : q === 'filter-deleting' ? 'Deleting' : 'All'); if (q === 'delete-confirm') { setSelectedId(1); setPanel('delete') } if (q === 'data-controls') setPanel('data') }) }, [])
  const rows = useMemo(() => filter === 'Shared' ? looks.filter(x => x.shared) : filter === 'Deleting' ? looks.filter(x => x.deleting) : looks, [filter])
  const empty = fixture === 'empty'; const skeleton = fixture === 'skeleton'; const error = fixture === 'error'; const offline = fixture === 'offline-cached'; const low = fixture === 'low-confidence';
  const selectedLook = looks.find(look => look.id === selectedId) ?? looks[0]
  const overlay = panel ? <E1Modal label={panel === 'delete' ? `Delete ${selectedLook.name}` : 'Try-on history data controls'} onClose={() => setPanel(null)}><div className="flex justify-between"><h2 className="text-[18px] font-semibold">{panel === 'delete' ? `Delete ${selectedLook.name}?` : 'History privacy controls'}</h2><button aria-label="Close dialog" className="grid h-11 w-11 place-items-center" onClick={() => setPanel(null)}><X /></button></div>{panel === 'delete' ? <><p className="mt-3 text-[13px] text-white/70">{selectedLook.source} · generated look and its local identifier move to pending deletion. The source photo is handled separately.</p><div className="mt-4 flex gap-2"><BtnSecondary onClick={() => setPanel(null)}>Cancel</BtnSecondary><BtnGhost onClick={() => { setStatus(`${selectedLook.name} moved to delete pending.`); setPanel(null) }}>Confirm delete</BtnGhost></div></> : <><p className="mt-3 text-[13px] text-white/70">Photo-adjacent history · local fixtures · this history only · refreshed May 21 · per-row confidence · retained until deleted.</p><ConsentRail controls={FULL_DATA_CONTROLS} /></>}</E1Modal> : undefined
  return <HifiShell header={<TopBar title={<>Try-on <span className="text-emphasis">history</span></>} />} atmosphere="you" showTabBar={false} overlay={overlay}><main data-f2-state={`87-${fixture}`} className="space-y-4 px-4 pb-8 pt-3">
    <GlassCard tone="you"><p className="text-[11px] uppercase tracking-widest text-white/50">Saved looks</p>{skeleton ? <div className="mt-3 h-14 animate-pulse rounded-xl bg-white/5" /> : <><p className="mt-1 text-[24px] font-semibold">{empty ? 'No saved looks' : `${rows.length} shown of 7`}</p><p className="mt-2 text-[12px] text-white/60">Source: local try-on history · refreshed May 21, 10:20 · {low ? 'sync stale · low confidence' : 'confirmed'}</p></>}</GlassCard>
    <div role="tablist" aria-label="Try-on history filters" className="grid grid-cols-4 gap-1">{['All','Saved','Shared','Deleting'].map(x => <button key={x} role="tab" aria-selected={filter === x} className={cx('min-h-11 rounded-xl text-[12px]', filter === x ? 'bg-white/10 text-white' : 'text-white/55')} onClick={() => setFilter(x)}>{x}</button>)}</div>
    {(error || offline) && <SolidCard><p role="alert" className="font-semibold">{error ? 'History sync failed' : 'Offline · cached history'}</p><p className="mt-1 text-[12px] text-white/60">Cached rows remain. Local-ID deletion is available.</p><BtnSecondary className="mt-3" onClick={() => setStatus('Retry completed locally; no network request was made.')}>Retry</BtnSecondary></SolidCard>}
    {empty ? <SolidCard><p className="font-semibold">No try-on history yet</p><Link href="/screens/86" className="focus-ring mt-3 flex min-h-11 items-center text-brand-orange">Create a privacy-safe preview</Link></SolidCard> : !skeleton && <div className="space-y-2">{rows.map(row => <SolidCard key={row.id}><div className="flex gap-3"><div data-asset-disposition="HIFI-87-01-code-native-no-identifiable-person" role="img" aria-label="Privacy-safe garment thumbnail, no identifiable person" className="grid h-14 w-14 shrink-0 place-items-center rounded-xl bg-white/5"><Camera className="text-white/35" /></div><div className="min-w-0 flex-1"><h3 className="font-semibold">{row.name}</h3><p className="mt-1 text-[12px] text-white/60">{row.source} · render {row.render} · retention until deletion · {row.shared ? 'shared May 21' : 'never shared'}</p><div className="mt-2 flex gap-1"><BtnGhost quiet onClick={() => setStatus(`${row.name} prompt loaded locally for screen 86.`)}><RotateCcw />Reuse</BtnGhost><BtnGhost quiet onClick={() => { setSelectedId(row.id); setPanel('delete') }}><Trash2 />Delete</BtnGhost></div></div></div></SolidCard>)}</div>}
    {fixture === 'reuse-success' && <Chip tone="done">Prompt ready for Virtual try-on</Chip>}{fixture === 'delete-pending' && <Chip>Deletion pending · 2 shown of 6</Chip>}<Provenance items={['Try-on history · local fixture', 'Fresh May 21 · 10:20']} /><BtnGhost onClick={() => setPanel('data')}>Data controls</BtnGhost><p role="status" className="text-[12px] text-white/60">{status}</p>
  </main></HifiShell>
}
